### ISSUE TITLE
Head initialization failure

### ISSUE THREAD

**Issue by v0d1ch** [obsidiansystems/hydra-pay#10]
When running the demo locally (tag `c9de54b1d452e42a9e106f71a4397e3b2ac54377`) I am experiencing error:

```
   Failed to submit tx, check participants fuel
```

This happens both on the demo frontend and when trying to send socket messages using postman. 

Initially I though that just the readme sections are a bit out of order since it makes sense to fund the address/es first before initializing the head, but funding and then initializing didn't work. When initializing the head I can see addresses are not funded:

```
{
    "tagged_payload": {
        "tag": "HeadInfo",
        "contents": {
            "headStatus_name": "test",
            "headStatus_balances": {
                "addr_test1vq8lkpxf42m9k4e7f34dmhdutquhvakwyyqqqkq5a82v6rcqenqh3": 0,
                "addr_test1vr747rl3x752krr86v2laglz4h2pfwh05xud04q5h874wucu8k3c3": 0
            },
            "headStatus_running": true,
            "headStatus_status": "Status_Pending"
        }
    },
    "tagged_id": 0
}
```

**Comment by Yasuke** [comment]
@v0d1ch It looks like not enough fuel was given to the proxy addresses to be able to initialize the head. Can you tell me who much fuel was given to each participant?

The order is purposeful: Funding/Fuel must happen first, then you may Initialize the Head as that requires an L1 operation.

The error `failed to submit tx, check participants fuel` tells me that one or more participants didn't have fuel and thus the Hydra Node complained with NotEnoughFuel.

I would say try again and ensure you give adequate fuel to each participant you want in the head, and please let me know if the issue persists.

**Comment by v0d1ch** [comment]
Thanks for looking at this @Yasuke

**Comment by parenthetical** [comment]
@v0d1ch this might be because the readme lists the commands in the wrong order. You should first add funds and fuel to your proxy address (see https://github.com/obsidiansystems/hydra-pay#add-funds, don't forget to submit the transactions the API endpoint returns).

**Comment by v0d1ch** [comment]
Oh, sorry. I wanted to say I followed the instructions in the _live documentation_ after running the demo. Those should work and be in the right order right?

**Comment by parenthetical** [comment]
Yes, that's right. Are you able to run through the live docs in order, funding both fuel and regular while pressing the green button to submit the transaction? This is different from the button which queries the API for a funding transaction. If you're trying to make a head with two addresses you'll have to press both the "get transaction" and green "submit transaction" buttons four times in total.

**Comment by v0d1ch** [comment]
Ok at first I thought the tag I am using is broken tag `c9de54b1d452e42a9e106f71a4397e3b2ac54377` but then I pulled the latest develop branch `3437c408c09f4b3fbf50c9ad56a320a2243375dd` and still have problems running the demo locally.

I am attaching the [video](https://user-images.githubusercontent.com/1666357/207394115-65045a2d-d3a6-449a-82b9-98ffc37b62d9.webm) so you guys can have easier time figuring out what could have gone wrong here. 

This is the redacted error message since it is huge, looks like argument is missing when calling cardano-cli:

```
...
    "contents": "Cardano CLI: Missing: (--tx-in TX-IN)
...
```

**Comment by Yasuke** [comment]
@v0d1ch You have been copying the example addresses from the expected response, and not the actual addresses generated by your hydra pay instance. Here is a video on the same hash showing things working: 

[video](https://user-images.githubusercontent.com/6433135/207403437-807672d4-ff5c-450a-a66f-fc247f61628d.mp4)

There is convenience copy paste buttons for any and all the addresses at any point they are returned from Hydra Pay, so using those will save you a lot of trouble in the future.

**Comment by v0d1ch** [comment]
Thanks, I'll give it another shot. Copy button didn't work for me for whatever reason, I'll try different browser and report back.

**Comment by v0d1ch** [comment]
Ok, tried it on firefox and works really nicely, good job!

 I am not sure why copy button on chrome didn't work for me but that is probably something on my end. I tested nixos and docker workflow and both work fine.
