### ISSUE TITLE
Cannot run Docker image on M1 Mac

### ISSUE THREAD

**Issue by trevinwisaksana** [obsidiansystems/hydra-pay#22]
Hi,

I have an issue with running the hydra-pay Docker image on my M1 MacBook Pro. I am getting a warning when attempting to run 

`docker run -p 127.0.0.1:8000:8000/tcp --name hydra-pay obsidiansys/hydra-pay:latest`

`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

It exits shortly after and it still fails even when I try to run in with this tag: `--platform linux/amd64`

Do you have any suggestions to work around this? Thanks!

**Comment by Yasuke** [comment]
Hi @trevinwisaksana,

Thank you for reaching out, at the time of our first Hydra Pay release, the cardano binary dependencies didn't work on mac/m1, so the currently available container will not run on M1.

The `--platform linux/amd64` argument changes the platform of the container, but the compiled binaries that exist in the image are unable to run on that platform, and the issue then persists. 

Fortunately the underlying binaries are now supported (as of this month), and there is some exciting changes coming to the library. In response to your issue we have kicked off some builds and testing to confirm support, and when we have confirmation that Hydra Pay runs under M1 either by rosetta emulation, or natively, we will provide a new image that will resolve your problem.

For now I can only recommend running on a different device or under a linux virtual machine, until we can get an updated image on docker hub.

**Comment by trevinwisaksana** [comment]
Sounds good! Thanks for the info. Looking forward to it!
