### ISSUE TITLE
Readme out of sync

### ISSUE THREAD

**Issue by v0d1ch** [obsidiansystems/hydra-pay#3]
I know this is a work in progress but `README.md` is not in sync with the current state in the code. There is a wrapper called `tagged_payload` and a field `tagged_id` but it is missing in the examples.

**Comment by Yasuke** [comment]
@v0d1ch The documentation mentions that all requests must be tagged to interact with Hydra Pay, and there is an example that shows that tagging process. The rest of the documentation shows the unique payloads without the tagging as that cuts down on a tremendous amount of noise.

The live documentation also covers this and shows the shape of the request in realtime.

**Comment by v0d1ch** [comment]
My idea was to have people that want to use HydraPay have really nice experience. If you think `tagged_payload` brings too much noise can we at least add appropriate `tag` field in the examples? 

For instance, there is this piece of json in the readme:

```
{
  "headCreate_name": "test",
  "headCreate_participants": [
    "addr_test1vpperccj7n8faw74ketx68k2mehg23d864hvg209cgupp5c4r47hp"
  ],
}

```
If I just _tag_ this payload I will get `InvalidMessage` (which is another point I wanted to mention) and users will have problems figuring out that they also need to add field `tag` with the value  `CreateHead`. 

The situation is similar for this _payload_ also:

```
{
  "headInit_name": "test",
  "headInit_participant": "addr_test1vpperccj7n8faw74ketx68k2mehg23d864hvg209cgupp5c4r47hp"
}
```
**BUT** here we there is also additional missing field `headInit_contestation` so that's why I said that readme is not in sync with  the current code in the repo.

**Comment by v0d1ch** [comment]
@Yasuke do you think I should create a new issue or you can re-open this one related to the observations above?
