### ISSUE TITLE
Shell.nix?

### ISSUE THREAD

**Issue by v0d1ch** [obsidiansystems/hydra-pay#4]
This is minor but can we have `shell.nix` with `cardano-cli` binary exposed? It shouldn't be a lot of work, we would need it to fund the proxy addresses at least and I think it adds value to the dev UX.

**Comment by ali-abrar** [comment]
#9

**Comment by v0d1ch** [comment]
Implemented here https://github.com/obsidiansystems/hydra-pay/pull/9
